[build]
  base = "/"
  command = "cd youtube-downloader-frontend && npm install && npm run build"
  publish = "youtube-downloader-frontend/dist"
  functions = "netlify/functions"

[functions]
  # Configuración general para TODAS las funciones
  node_bundler = "esbuild"
  node_version = "20" # ¡Aquí sí es una cadena directamente bajo [functions]!
  # Nota: Si tuvieras configuraciones específicas por función (ej. funciones.nombre_de_funcion),
  # entonces node_version iría dentro de un objeto "[functions.nombre_de_funcion]".
  # Pero para una configuración global, va directamente aquí.

# Redirecciones y reescrituras
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api_handler/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200