services:
  - type: web
    name: youtube-downloader-api
    env: node
    rootDir: api
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheck:
      path: /healthz
      initialDelaySeconds: 120  
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_COOKIE
        sync: false 
      - key: CORS_ORIGIN
        sync: false