services:
  - type: web
    name: youtube-downloader-api  
    env: node                     
    rootDir: api                  
    plan: free                    
    buildCommand: "npm install"   
    startCommand: "npm start"     
    healthCheckPath: /healthz     
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        generateValue: true