# render.yaml
services:
  - type: web
    name: youtube-downloader-api
    rootDir: api
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: CORS_ORIGIN
        value: https://youtube-downloader-phi-pearl.vercel.app/ 
    healthCheckPath: /healthz
    plan: free
    autoDeploy: true
    buildpacks:
      - url: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git